// Housekeeping for src/generated (STACK-03), run by `pnpm generate`:
//   node scripts/generated.mjs clean   remove src/generated so stale files never survive
//   node scripts/generated.mjs header  put the "@generated" header on line 1 of every file
// tools/ci/check_generated_header.py fails CI when a generated file lacks the header.
import { existsSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const HEADER = "// @generated by packages/api-client — do not edit";
const root = fileURLToPath(new URL("../src/generated", import.meta.url));

function walk(dir) {
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const path = join(dir, name);
      return statSync(path).isDirectory() ? walk(path) : [path];
    });
}

const command = process.argv[2];
if (command === "clean") {
  rmSync(root, { recursive: true, force: true });
} else if (command === "header") {
  if (!existsSync(root)) throw new Error(`${root} does not exist; run the generators first`);
  for (const file of walk(root)) {
    const text = readFileSync(file, "utf8");
    if (text.split("\n", 1)[0] !== HEADER) writeFileSync(file, `${HEADER}\n${text}`);
  }
} else {
  console.error("usage: node scripts/generated.mjs clean|header");
  process.exit(2);
}
