"""tools/keycloak_messages.py (IDENTITY-01 step 3): terminology keys -> Keycloak messages."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parents[2]


def _load() -> ModuleType:
    spec = importlib.util.spec_from_file_location("keycloak_messages", ROOT / "tools" / "keycloak_messages.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["keycloak_messages"] = module
    spec.loader.exec_module(module)
    return module


km = _load()


def _all_terms(**overrides: str) -> dict[str, str]:
    terms = {term: f"value for {term}" for _, term in km.MESSAGE_MAP}
    terms.update(overrides)
    return terms


def test_render_maps_terms_to_keycloak_keys() -> None:
    text = km.render(terms=_all_terms(**{"auth.login.submit": "Sign in"}))
    assert "doLogIn=Sign in" in text.splitlines()
    assert text.startswith("# @generated by tools/keycloak_messages.py")


def test_missing_term_raises_key_error_naming_the_key() -> None:
    terms = _all_terms()
    del terms["auth.login.submit"]
    with pytest.raises(KeyError, match=r"auth\.login\.submit"):
        km.render(terms=terms)


def test_apostrophes_are_doubled_for_message_format() -> None:
    text = km.render(terms=_all_terms(**{"auth.login.title": "Don't panic"}))
    assert "loginAccountTitle=Don''t panic" in text.splitlines()


def test_values_are_escaped_for_properties() -> None:
    text = km.render(terms=_all_terms(**{"auth.login.title": "a\\b\nc"}))
    assert "loginAccountTitle=a\\\\b\\nc" in text.splitlines()


def test_committed_file_is_up_to_date() -> None:
    assert km.main(["--check"]) == 0


def test_check_fails_when_the_file_differs(tmp_path: Path) -> None:
    out = tmp_path / "messages_en.properties"
    out.write_text("stale\n", encoding="utf-8")
    assert km.main(["--check", "--output", str(out)]) == 1
    assert km.main(["--output", str(out)]) == 0
    assert km.main(["--check", "--output", str(out)]) == 0


def test_every_mapped_term_exists_in_the_dictionary() -> None:
    terms = km.load_terms()
    assert {term for _, term in km.MESSAGE_MAP} <= set(terms)
