#!/usr/bin/env python3
"""Fail when a generated API client file lacks the ``@generated`` header (STACK-03). Stdlib only.

    python3 tools/ci/check_generated_header.py [DIR]

DIR defaults to ``packages/api-client/src/generated``. Every file under it must start with the
header line written by ``packages/api-client/scripts/generated.mjs``. A missing header means the
file was hand-written or hand-edited; regenerate with ``pnpm --filter api-client generate``.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DIR = ROOT / "packages" / "api-client" / "src" / "generated"
HEADER = "// @generated by packages/api-client — do not edit"


def missing_header(directory: Path) -> list[Path]:
    """Files under ``directory`` whose first line is not the header, sorted."""
    bad: list[Path] = []
    for path in sorted(p for p in directory.rglob("*") if p.is_file()):
        with path.open(encoding="utf-8", errors="replace") as handle:
            first = handle.readline().rstrip("\r\n")
        if first != HEADER:
            bad.append(path)
    return bad


def main(argv: list[str]) -> int:
    directory = Path(argv[0]) if argv else DEFAULT_DIR
    if not directory.is_dir():
        print(f"error: {directory} is not a directory", file=sys.stderr)
        return 2
    if not any(p.is_file() for p in directory.rglob("*")):
        print(f"error: {directory} has no generated files", file=sys.stderr)
        return 2
    bad = missing_header(directory)
    for path in bad:
        print(f"{path}: first line must be {HEADER!r} (regenerate; never hand-edit)")
    if bad:
        return 1
    print(f"ok: every file under {directory} has the @generated header")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
