"""Tests for tools/ci/check_generated_header.py (STACK-03). Stdlib only.

Run from the repo root: python3 -m unittest tools/ci/test_check_generated_header.py
Tests work on temp copies; they never write into the real repo tree.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "tools" / "ci" / "check_generated_header.py"
GENERATED = ROOT / "packages" / "api-client" / "src" / "generated"
HEADER = "// @generated by packages/api-client — do not edit"


def run(root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), str(root)],
        capture_output=True,
        text=True,
        check=False,
    )


class HeaderCheckTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp)
        self.generated = self.tmp / "generated"
        shutil.copytree(GENERATED, self.generated)

    def test_committed_generated_files_all_have_the_header(self) -> None:
        result = run(GENERATED)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_generated_tree_is_not_empty(self) -> None:
        files = [p for p in GENERATED.rglob("*") if p.is_file()]
        self.assertGreater(len(files), 0)

    def test_missing_header_fails_and_names_the_file(self) -> None:
        target = self.generated / "schema.ts"
        lines = target.read_text(encoding="utf-8").splitlines(keepends=True)
        self.assertEqual(lines[0].rstrip("\n"), HEADER)
        target.write_text("".join(lines[1:]), encoding="utf-8")
        result = run(self.generated)
        self.assertEqual(result.returncode, 1)
        self.assertIn("schema.ts", result.stdout + result.stderr)

    def test_header_not_on_first_line_fails(self) -> None:
        target = self.generated / "schema.ts"
        target.write_text("// hand edit\n" + target.read_text(encoding="utf-8"), encoding="utf-8")
        result = run(self.generated)
        self.assertEqual(result.returncode, 1)
        self.assertIn("schema.ts", result.stdout + result.stderr)

    def test_missing_directory_fails(self) -> None:
        result = run(self.tmp / "nope")
        self.assertNotEqual(result.returncode, 0)


if __name__ == "__main__":
    unittest.main()
