#!/usr/bin/env python3
"""Generate ``docs/architecture/module-map.md`` from the module registry (ARCH-02).

  uv run python tools/gen_module_map.py            # rewrite the committed map
  uv run python tools/gen_module_map.py --check    # exit 1 if the committed map is stale

The output is a table of modules in mount order plus a Mermaid ``graph TD`` of dependencies.
It is sorted and carries no timestamps, so two runs give byte-identical files. Disabled modules
(``AIP_DISABLED_MODULES``) are ignored: the map always shows every module.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API_DIR = ROOT / "apps" / "api"
DEFAULT_OUTPUT = ROOT / "docs" / "architecture" / "module-map.md"

sys.path.insert(0, str(API_DIR))

from aip.platform.modules.registry import (  # noqa: E402
    DEFAULT_MODULES_PACKAGE,
    LoadedModule,
    RegistryError,
    discover,
    resolve,
)


def _code(values: list[str]) -> str:
    return ", ".join(f"`{v}`" for v in values) if values else "none"


def render(modules: list[LoadedModule]) -> str:
    lines = [
        "# Module map",
        "",
        "<!-- Generated by tools/gen_module_map.py (ARCH-02). Do not edit by hand. -->",
        "",
        "Modules in mount order: each module is mounted after the modules it depends on.",
        "Regenerate with `uv run python tools/gen_module_map.py`.",
        "",
        "| Order | Module | Context | Depends on |",
        "|---|---|---|---|",
    ]
    for index, module in enumerate(modules, start=1):
        deps = sorted(module.manifest.depends_on)
        lines.append(f"| {index} | `{module.id}` | {module.manifest.context} | {_code(deps)} |")
    if not modules:
        lines.append("| | none yet | | |")

    lines += ["", "## Dependencies", "", "An arrow `a --> b` means module a depends on b.", ""]
    lines += ["```mermaid", "graph TD"]
    for module in sorted(modules, key=lambda m: m.id):
        deps = sorted(module.manifest.depends_on)
        if not deps:
            lines.append(f"    {module.id}")
        lines.extend(f"    {module.id} --> {dep}" for dep in deps)
    lines += ["```", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--package", default=DEFAULT_MODULES_PACKAGE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args(argv)
    output: Path = args.output

    try:
        text = render(resolve(discover(args.package)))
    except RegistryError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.check:
        current = output.read_text(encoding="utf-8") if output.is_file() else None
        if current != text:
            print(
                f"{output} is out of date; run `uv run python tools/gen_module_map.py`",
                file=sys.stderr,
            )
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
