#!/usr/bin/env python3
"""Generate the ``aip`` Keycloak login theme's messages from terminology keys (IDENTITY-01).

    python3 tools/keycloak_messages.py           # write the properties file
    python3 tools/keycloak_messages.py --check   # exit 1 if the committed file differs (CI)

Labels on the Keycloak login pages come from ``config/terms/en-AU/auth.json`` through the explicit
``MESSAGE_MAP`` below (Keycloak message key -> terminology key). One term may feed several Keycloak
keys. Keycloak formats every message with ``java.text.MessageFormat``, so apostrophes are doubled.
Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TERMS_FILE = ROOT / "config" / "terms" / "en-AU" / "auth.json"
OUTPUT = (
    ROOT / "infra" / "keycloak" / "themes" / "aip" / "login" / "messages" / "messages_en.properties"
)
HEADER = (
    "# @generated by tools/keycloak_messages.py from config/terms/en-AU/auth.json - do not edit"
)

# (Keycloak message key, terminology key). Order is the output order.
MESSAGE_MAP: tuple[tuple[str, str], ...] = (
    ("loginAccountTitle", "auth.login.title"),
    ("usernameOrEmail", "auth.login.email"),
    ("email", "auth.login.email"),
    ("password", "auth.login.password"),
    ("doLogIn", "auth.login.submit"),
    ("doForgotPassword", "auth.login.forgotPassword"),
    ("invalidUserMessage", "auth.login.invalidCredentials"),
    ("loginTotpTitle", "auth.otp.title"),
    ("loginOtpOneTime", "auth.otp.code"),
    ("passkey-login-title", "auth.passkey.title"),
    ("webauthn-login-title", "auth.passkey.title"),
    ("passkey-doAuthenticate", "auth.passkey.signIn"),
    ("webauthn-doAuthenticate", "auth.passkey.signIn"),
)


def _escape(value: str) -> str:
    value = value.replace("'", "''")  # MessageFormat quoting
    out = value.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return "\\" + out if out.startswith(" ") else out


def render(*, terms: Mapping[str, str]) -> str:
    """The properties file for ``terms``; ``KeyError`` names a mapped term missing from it."""
    lines = [HEADER]
    for kc_key, term_key in MESSAGE_MAP:
        if term_key not in terms:
            raise KeyError(
                f"terminology key {term_key} (for Keycloak {kc_key}) is not in auth.json"
            )
        lines.append(f"{kc_key}={_escape(terms[term_key])}")
    return "\n".join(lines) + "\n"


def load_terms(path: Path = TERMS_FILE) -> dict[str, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a JSON object of term key -> text")
    return {str(k): str(v) for k, v in data.items()}  # pyright: ignore[reportUnknownVariableType, reportUnknownArgumentType]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the output file differs")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--terms", type=Path, default=TERMS_FILE)
    args = parser.parse_args(argv)

    text = render(terms=load_terms(args.terms))
    output: Path = args.output
    if args.check:
        current = output.read_text(encoding="utf-8") if output.is_file() else None
        if current != text:
            print(f"{output} is out of date: run python3 tools/keycloak_messages.py")
            return 1
        print(f"ok: {output} matches {args.terms}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
